# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Y:/ECOP/222/project_1/project_1.cache/wt [current_project]
set_property parent.project_path Y:/ECOP/222/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  //Mac/Home/Downloads/Single_cycled_CPU-master/RegisterFile.v
  //Mac/Home/Downloads/Single_cycled_CPU-master/InstructionMemory.v
  //Mac/Home/Downloads/Single_cycled_CPU-master/Extend.v
  //Mac/Home/Downloads/Single_cycled_CPU-master/DataMemory.v
  //Mac/Home/Downloads/Single_cycled_CPU-master/ControlUnit.v
  //Mac/Home/Downloads/Single_cycled_CPU-master/ALU.v
  //Mac/Home/Downloads/Single_cycled_CPU-master/my_cpu.v
}
synth_design -top my_cpu -part xc7a35tcpg236-1
write_checkpoint -noxdef my_cpu.dcp
catch { report_utilization -file my_cpu_utilization_synth.rpt -pb my_cpu_utilization_synth.pb }
